name: Build and Test

on: [push, pull_request_review]

jobs:
  Build-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Install Dependencies
        run: make deps
      - name: Build
        run: make build
      - name: Test
        run: make test
      - name: Benchmark
        run: make benchmark
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mnemo
          path: ./bin
          if-no-files-found: error
